server: 
      port: 8002
eureka: 
      instance: 
         hostname: eureka8002.com
      client: 
         registerWithEureka: false
         fetchRegistry: false
         serviceUrl:
   #         defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
             defaultZone: http://eureka8001.com:8001/eureka,http://eureka8003.com:8003/eureka  
      